config/routes.rb
Rails.application.routes.draw do
  root 'durians#index'

  # Routes for Durian
  get '/durians' => 'durians#index', as: 'durians'
  get '/durians/compare' => 'durians#compare_price'


  # Routes for Order
  get '/orders/payment' => 'orders#payment', as: 'payment'
  get '/orders/payment/success/:id' => 'orders#payment_success'

  post '/orders/payment/webhook' => 'orders#payment_webhook'

  # Routes for Shopping Cart
  get '/shoppingcarts' => 'shoppingcarts#index', as: 'shoppingcarts'
  get '/shoppingcarts/checkout' => 'shoppingcarts#checkout'
  get '/shoppingcarts/confirmation' => 'shoppingcarts#confirmation', as: 'confirmation'

  post '/shoppingcarts/delivery' => 'shoppingcarts#set_delivery_details', as: 'set_delivery_details'

  post '/shoppingcarts/cart' => 'shoppingcarts#add_item', as: 'shoppingcarts_add'
  post '/shoppingcarts/plus' => 'shoppingcarts#plus_weight', as: 'shoppingcarts_plus'
  post '/shoppingcarts/minus' => 'shoppingcarts#minus_weight', as: 'shoppingcarts_minus'
  post '/shoppingcarts/delete' => 'shoppingcarts#delete_item', as: 'shoppingcarts_delete'

end

app/controllers/shoppingcarts_controller.rb
class ShoppingcartsController < ApplicationController
# a way to turn off CSRF that won't render a null session
skip_before_action :verify_authenticity_token

  def index
    @payment_amount = 0

    session["cart"].each do |item|
      @payment_amount += item["price_per_kg"].to_i * item["weight"].to_i
    end
  end

  def checkout
    if shopping_cart_valid? == false
      redirect_to root_path
    end
  end


  def set_delivery_details
     session["delivery_details"] = delivery_params
     redirect_to confirmation_path
  end

  def confirmation
    if shopping_cart_valid? == false
      redirect_to root_path
    end

    @payment_amount = 0

    session["cart"].each do |item|
      @payment_amount += item["price_per_kg"].to_i * item["weight"].to_i
    end

  end

  def plus_weight
    order_to_addWeight = JSON.parse(request.body.read)

    @updatedWeight = 0
    @updatedTotalPrice = 0

    session["cart"].each do |durian|
      if durian["id"] == order_to_addWeight["id"]
        durian["weight"] = durian["weight"].to_i + 1
        @updatedTotalPrice = durian["weight"].to_i * durian["price_per_kg"].to_i

        durian["weight"] = durian['weight'].to_s
        @updatedWeight = durian["weight"]
      end
    end

    @payment_amount = 0

    session["cart"].each do |item|
      @payment_amount += item["price_per_kg"].to_i * item["weight"].to_i
    end

    render :json => { weight: @updatedWeight, total_price: @updatedTotalPrice, total_amount: @payment_amount }
  end

  def minus_weight
    order_to_subtractWeight = JSON.parse(request.body.read)

    @updatedWeight = 0
    @updatedTotalPrice = 0

    session["cart"].each do |durian|
      if durian["id"] == order_to_subtractWeight["id"]
        durian["weight"] = durian["weight"].to_i - 1
        @updatedTotalPrice = durian["weight"].to_i * durian["price_per_kg"].to_i

        durian["weight"] = durian['weight'].to_s
        @updatedWeight = durian["weight"]
      end
    end

    @payment_amount = 0

    session["cart"].each do |item|
      @payment_amount += item["price_per_kg"].to_i * item["weight"].to_i
    end

    render :json => { weight: @updatedWeight, total_price: @updatedTotalPrice, total_amount: @payment_amount }
  end

  def delete_item
    order_to_delete = JSON.parse(request.body.read)

    session["cart"].each do |durian|
      if durian["id"] == order_to_delete["id"]
        session["cart"].delete_if { |hash| hash["id"] == order_to_delete["id"] }
      end
    end

    @payment_amount = 0

    session["cart"].each do |item|
      @payment_amount += item["price_per_kg"].to_i * item["weight"].to_i
    end

      render :json => { cart: session["cart"], amount: @payment_amount }
  end


  def add_item
    found = false;

    # converting request.body which is in string (ajax.js) to JSON object
    current_order = JSON.parse(request.body.read)

    # if the cart is empty, add the durian in the cart
    if session["cart"].length == 0
      session["cart"] << current_order
      found = true
      render :json => session["cart"]
    else
      # else if the cart is not empty, and if the same durian was added, increment the weight of that matched durian but do not add a new durian entry into cart
      session["cart"].each do |durian|
        if durian["id"] == current_order["id"]
          durian['weight'] = durian['weight'].to_i + current_order["weight"].to_i
          durian['weight'] = durian['weight'].to_s
          found = true
        end
      end

      # if a new durian was added
      if found == false
        session["cart"] << current_order
      end

      render :json => session["cart"]
    end

end


private
  def post_params
    params.require(:durian).permit(:id, :name, :price_per_kg, :weight, :image_url)
  end

  def delivery_params
    params.require(:delivery).permit(:name, :email, :contact_number, :comment, :postal_code, :unit_number, :address, :date, :time)
  end

end

app/views/shoppingcarts/checkout.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<!--Payment Progress -->
<div class="checkout-page-title page-title">
	<div class="page-title-inner flex-row medium-flex-wrap container">
	  <div class="flex-col flex-grow medium-text-center">
  	 	 <nav class="breadcrumbs heading-font checkout-breadcrumbs text-center h2 strong">
    	   <a href="/shoppingcarts" class="cart-greyout">Shopping Cart</a>
    	   <span class="divider hide-for-small"><i class="icon-angle-right"></i></span>
    	   <a href="/shoppingcarts/checkout" class="current">Checkout</a>
    	   <span class="divider hide-for-small"><i class="icon-angle-right"></i></span>
    	   <a href="/shoppingcarts/confirmation" class="cart-greyout">Order Confirmation</a>
		 </nav>
	  </div><!-- .flex-left -->
	</div><!-- flex-row -->
</div>


<div class="container mb-4">

<h2>Contact Details</h2>

<%= form_with scope: :delivery, url: set_delivery_details_path, local: true do |form| %>

<div class="container">
	<div class="row">
		<div class="col-3">
  		Name:<br>
  		<%= form.text_field :name, class: "form-control", value: session["delivery_details"]["name"] %>
		</div>
		<div class="col-3">
  		Email:<br>
  		<%= form.email_field :email, class: "form-control", value: session["delivery_details"]["email"] %>
		</div>
		<div class="col-3">
  		Contact Number:<br>
  		<%= form.number_field :contact_number, class: "form-control", value: session["delivery_details"]["contact_number"] %>
		</div>
	</div>
<br>
	<div class="row">
		<div class="col-9">
  		Add Comments About Your Order:<br>
  		<%= form.text_area :comment, class: "form-control", rows: "3", value: session["delivery_details"]["comment"] %>
		</div>
	</div>

</div>


<hr/>
<h2>Delivery Details</h2>

<div class="container">
	<div class="row">
		<div class="col-4">
  		Postal Code:<br>
  		<%= form.number_field :postal_code, class: "form-control", value: session["delivery_details"]["postal_code"] %>
		</div>

		<div class="col-4">
			Unit Number:<br>
			<%= form.text_field :unit_number, class: "form-control", value: session["delivery_details"]["unit_number"] %>
		</div>
	</div>

	<br>

	<div class="row">
		<div class="col-8">
			Address:<br>
			<%= form.text_field :address, class: "form-control", value: session["delivery_details"]["address"] %>
		</div>
	</div>

	<br>

	<div class="row">
		<div class="col-4">
			Delivery Date:<br>
			<%= form.date_field :date, class: "form-control" , value: session["delivery_details"]["date"] %>
		</div>

		<div class="col-4">
			Delivery Time:<br>

			<%= form.select :time, options_for_select([ "10.00am - 12.00pm", "11.00am - 1.00pm", "3.00pm - 5.00pm", "5.00pm - 7.00pm"], session["delivery_details"]["time"]), {}, { :class => 'form-control' }  %>
		</div>
	</div>

</div>

<br>

<div class="col mb-2">
    <div class="row">
        <div class="col-sm-8 col-md-4">
        	<a href="/shoppingcarts" class='btn btn-block btn-outline-primary'>Back to Shopping Cart</a>
        </div>

        <div class="col-sm-8 col-md-4 text-right">
        	<%= form.submit 'Next', class: "btn btn-success btn-block"%>
        </div>
    </div>
</div>




<%end%>

</div>

app/views/shoppingcarts/confirmation.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<!--Payment Progress -->
<div class="checkout-page-title page-title">
	<div class="page-title-inner flex-row medium-flex-wrap container">
	  <div class="flex-col flex-grow medium-text-center">
  	 	 <nav class="breadcrumbs heading-font checkout-breadcrumbs text-center h2 strong">
    	   <a href="/shoppingcarts" class="cart-greyout	">Shopping Cart</a>
    	   <span class="divider hide-for-small"><i class="icon-angle-right"></i></span>
    	   <a href="/shoppingcarts/checkout" class="cart-greyout">Checkout</a>
    	   <span class="divider hide-for-small"><i class="icon-angle-right"></i></span>
    	   <a href="/shoppingcarts/confirmation" class="current">Order Confirmation</a>
		 </nav>
	  </div><!-- .flex-left -->
	</div><!-- flex-row -->
</div>


<div class="container mb-4">
	<h2>Deliver To:</h2>

	<div class="container">
		<div class="row">
			<div>
	  		<%= session["delivery_details"]["name"]%>
			</div>

		</div>

		<div class="row">
			<div>
	  		<%= session["delivery_details"]["contact_number"]%>
			</div>
		</div>

		<div class="row">
			<div>
	  		<%= session["delivery_details"]["email"]%>
			</div>
		</div>

		<div class="row">
			<div class="capitalize">
				#<%= session["delivery_details"]["unit_number"] %>, <%=session["delivery_details"]["address"]%>
			</div>
		</div>

		<br>

		<div class="row">
			<div>
				<b>Delivery Date:</b> <%= Date.parse(session["delivery_details"]["date"]).strftime('%d %b %Y') %> from <%= session["delivery_details"]["time"] %>
			</div>
		</div>

		<div class="row">
			<div>
	  		<b>Comment:</b> <%= session["delivery_details"]["comment"]%>
			</div>
		</div>
	</div>

	<br>
	<br>

	<div class="table-responsive">
	    <table class="table table-striped">
	        <thead>
	            <tr>
	                <th scope="col"></th>
	                <th scope="col">Item</th>
	                <th scope="col">Price per kg</th>
	                <th scope="col">Weight</th>
	                <th scope="col" class="text-right">Total Price</th>
	            </tr>
	        </thead>
	        <tbody>
	        		<% session["cart"].each do |item| %>
	          		<tr>
	                  <td class="cart-image-column">
	                  	<%= image_tag(item["image_url"], :class => "cart-image") %>
	                  </td>

	                  <td>
	                  	<%= item["name"] %>
	                  </td>

	                  <td>
	                  	<%= "$" + (item["price_per_kg"].to_i/100).to_s %>/kg
	                  </td>

	                  <td>
	                  	<div class="form-row">
												<div class="col-md-3">
													<%= item["weight"] + "kg" %>
												</div>
											</div>
	                  </td>

	                  <td class="text-right">
	                  	<%= "$" + ((item["price_per_kg"].to_i * item["weight"].to_i)/100).to_s %>
	                  </td>

	              </tr>
	        		<% end %>

	            <tr>
	                <td></td>
	                <td></td>
	                <td></td>
	                <td><strong>Total</strong></td>
	                <td class="text-right"><strong><%= "$" + (@payment_amount/100).to_s %></strong></td>
	            </tr>

	        </tbody>
	    </table>
	</div>


	<div class="col mb-2">
	    <div class="row">
	        <div class="col-sm-12 col-md-6">
	        		<a href="/shoppingcarts/checkout" class='btn btn-block btn-outline-primary'>Back to Checkout</a>
	        </div>
	        <div class="col-sm-12 col-md-6 text-right">
	        		<button type='button' class='btn btn-primary btn-block btn-success' id='payment'>Confirm Order</button>
	        </div>
	    </div>
	</div>

</div>

app/views/shoppingcarts/index.html.erb
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<!--Payment Progress -->
<div class="checkout-page-title page-title">
	<div class="page-title-inner flex-row medium-flex-wrap container">
	  <div class="flex-col flex-grow medium-text-center">
  	 	 <nav class="breadcrumbs heading-font checkout-breadcrumbs text-center h2 strong">
    	   <a href="/shoppingcarts" class="current">Shopping Cart</a>
    	   <span class="divider hide-for-small"><i class="icon-angle-right"></i></span>
    	   <a href="/shoppingcarts/checkout" class="cart-greyout">Checkout</a>
    	   <span class="divider hide-for-small"><i class="icon-angle-right"></i></span>
    	   <a href="/shoppingcarts/confirmation" class="cart-greyout">Order Confirmation</a>
		 </nav>
	  </div><!-- .flex-left -->
	</div><!-- flex-row -->
</div>

<% if session["cart"].length === 0 %>
	<div class="empty">
	<br>
	<h3>You have a empty shopping cart</h3>
	<br>
</div>
<% else %>
	<div class="container mb-4">
	    <div class="row">
	        <div class="col-12">
	            <div class="table-responsive">
	                <table class="table table-striped">
	                    <thead>
	                        <tr>
	                            <th scope="col"></th>
	                            <th scope="col">Item</th>
	                            <th scope="col">Price per kg</th>
	                            <th scope="col" class="text-center">Weight</th>
	                            <th scope="col" class="text-right">Total Price</th>
	                            <th> </th>
	                        </tr>
	                    </thead>
	                    <tbody>
	                    		<% session["cart"].each do |item| %>
		                    		<tr>
		                            <td class="cart-image-column">
		                            	<%= image_tag(item["image_url"], :class => "cart-image") %>
		                            </td>

		                            <td>
		                            	<%= item["name"] %>
		                            </td>

		                            <td>
		                            	<%= "$" + (item["price_per_kg"].to_i/100).to_s %>/kg
		                            </td>

		                            <td>
		                            	<div class="cart-weight-column">
																		<div class="col-md-3">
																			<%= form_with scope: :durian, url: shoppingcarts_minus_path, class: "minus-btn", local: true do |form| %>
																			<%= form.hidden_field :id, :value => item["id"] %>
																			<%= form.submit '-', class: "btn btn-outline-dark", data: { disable_with: false }%>
																			<% end %>
																		</div>

																		&nbsp;&nbsp;&nbsp;

																		<div class="col-md-3" id='<%= item["id"] %>-weight'>
																			<%= item["weight"] + "kg" %>
																		</div>

																		&nbsp;&nbsp;

																		<div class="col-md-3">
																			<%= form_with scope: :durian, url: shoppingcarts_plus_path, class: "plus-btn", local: true do |form| %>
																			<%= form.hidden_field :id, :value => item["id"] %>
																			<%= form.submit '+', class: "btn btn-outline-dark", data: { disable_with: false } %>
																			<% end %>
																		</div>
																	</div>
		                          	</td>

		                            <td class="text-right" id='<%= item["id"] %>-total-price'>
		                            	<%= "$" + ((item["price_per_kg"].to_i * item["weight"].to_i)/100).to_s %>
		                            </td>

		                            <td class="text-right">
		                            	<%= form_with scope: :durian, url: shoppingcarts_delete_path, class: "remove-btn", local: true do |form| %>
																	<%= form.hidden_field :id, :value => item["id"] %>
																	<%= form.submit 'Remove', class: "btn btn-danger"%>
																	<% end %>
																</td>
		                        </tr>
	                    		<% end %>

	                        <tr>
	                            <td></td>
	                            <td></td>
	                            <td></td>
	                            <td></td>
	                            <td><strong>Total</strong></td>
	                            <td class="text-right"><strong id="payment_amount"><%= "$" + (@payment_amount/100).to_s %></strong></td>
	                        </tr>

	                    </tbody>
	                </table>
	            </div>
	        </div>

	        <div class="col mb-2">
	            <div class="row">
	                <div class="col-sm-12  col-md-6">
	                    <a href="/" class="btn btn-block btn-outline-primary">Continue Shopping</a>
	                </div>
	                <div class="col-sm-12 col-md-6 text-right">
	                    <a href="/shoppingcarts/checkout" class="btn btn-block btn-success">Checkout</a>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>
<% end %>