config/routes.rb
Rails.application.routes.draw do
  root 'durians#index'

  # Routes for Durian
  get '/durians' => 'durians#index', as: 'durians'
  get '/durians/compare' => 'durians#compare_price'


  # Routes for Order
  get '/orders/payment' => 'orders#payment', as: 'payment'
  get '/orders/payment/success/:id' => 'orders#payment_success'

  post '/orders/payment/webhook' => 'orders#payment_webhook'

  # Routes for Shopping Cart
  get '/shoppingcarts' => 'shoppingcarts#index', as: 'shoppingcarts'
  get '/shoppingcarts/checkout' => 'shoppingcarts#checkout'
  get '/shoppingcarts/confirmation' => 'shoppingcarts#confirmation', as: 'confirmation'

  post '/shoppingcarts/delivery' => 'shoppingcarts#set_delivery_details', as: 'set_delivery_details'

  post '/shoppingcarts/cart' => 'shoppingcarts#add_item', as: 'shoppingcarts_add'
  post '/shoppingcarts/plus' => 'shoppingcarts#plus_weight', as: 'shoppingcarts_plus'
  post '/shoppingcarts/minus' => 'shoppingcarts#minus_weight', as: 'shoppingcarts_minus'
  post '/shoppingcarts/delete' => 'shoppingcarts#delete_item', as: 'shoppingcarts_delete'

end

app/models/durian.rb
class Durian < ActiveRecord::Base
  has_many :order
  belongs_to :cream
  belongs_to :sweet
end

app/controllers/durians_controller.rb
require 'httparty'
require 'nokogiri'

class DuriansController < ApplicationController
  def index
    @durians = Durian.all

    if (session["cart"] == nil)
      session["cart"] = []
    end

    if (session["delivery_details"] == nil)
      session["delivery_details"] = {}
    end

  end

  def compare_price
    @products = []
    @url = "https://www.durianculture.com/product-category/durians/"

    doc = HTTParty.get(@url)
    @parse_page = Nokogiri::HTML(doc)

    scrapped_products = @parse_page.css(".product-type-simple")

    scrapped_products.each do |scrapped_product|

      @products.push( {
        "name" => scrapped_product.children[1].text.delete("\n\t").split("$")[0],
        "price" => scrapped_product.children[1].text.delete("\n\t").split("$")[1]
      })
    end

  end

end

app/views/durians/compare_price.html.erb
<div class="container mb-4 compare">
	<h2>Price Compare with Other Durian Store</h2>

	<h5><%= link_to @url, @url %></h5>

	<table class="table table-striped">
	    <thead>
	        <tr>
	            <th scope="col"></th>
	            <th scope="col">Item</th>
	            <th scope="col">Price per kg</th>
	        </tr>
	    </thead>
	    <tbody>
	    		<% @products.each_with_index do |product, index| %>
	      		<tr>
	              <td>
	              	<%= index + 1 %>
	              </td>

	              <td>
	              	<%= product["name"] %>
	              </td>

	              <td>
	              	<%= "$" + product["price"] %>
	              </td>
	          </tr>
	    		<% end %>
	    </tbody>
	</table>
</div>

app/views/durians/index.html.erb
<!-- Start: age Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">

    	<!-- Start: Hero Banner -->
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
									<%= image_tag "hero/banner1.jpg", class: "carouselImage"%>
                </div>
              </div>
            </div>
      <!-- End: Hero Banner -->

      <div class="row">

      	<% @durians.each do |durian| %>
	      	<div class="col-lg-4 col-md-6 mb-4">
	          <div class="card h-100">
	          	<%= image_tag(durian.image_url) %>
	            <div class="card-body">
	              <h4 class="card-title">
	                <%= durian.name %>
	              </h4>
	              <h5><%= "$" + (durian.price_per_kg/100).to_s %>/kg</h5>
	              <p class="card-text"><%= durian.description %></p>
	            </div>
	              <div class="addCartButton">
	                <div class="float-right">
	                	<%= form_with scope: :durian, url: shoppingcarts_add_path, class: "durian-form", local: true do |form| %>
										<%= form.hidden_field :id, :value => durian.id %>
										<%= form.hidden_field :name, :value => durian.name %>
										<%= form.hidden_field :image_url, :value => durian.image_url %>
								    <%= form.hidden_field :price_per_kg, :value => durian.price_per_kg %>
								    <%= form.hidden_field :weight, :value => 1 %>
								    <%= form.submit 'Add to cart', class: "btn btn-success btn-sm", "role" => "button", "data-container" => "body", "data-toggle" => "popover", "data-trigger" => "focus" ,"data-placement" => "top", "data-content" => "Added 1 kg of #{ durian.name } to your cart!", data: { disable_with: false } %>


								<% end %>
	                </div>
	              </div>
	            <div class="card-footer">
	            	<%	sweetness_rating = ""
	            		(1..5).each do |number|
		            		if number <= durian.sweet.name.to_i
		            			sweetness_rating += " ★"
		            		else
		            			sweetness_rating += " ☆"
		            		end
	            		end
	            	%>
	              <small class="text-muted">Sweetness <%= sweetness_rating%></small>

	              <br>
	              <%	creaminess_rating = ""
	            		(1..5).each do |number|
		            		if number <= durian.cream.name.to_i
		            			creaminess_rating += " ★"
		            		else
		            			creaminess_rating += " ☆"
		            		end
	            		end
	            	%>
	            	<small class="text-muted">Creaminess <%= creaminess_rating%></small>
	            </div>
	          </div>
	        </div>
	      <% end %>

			<br>

      </div>
      <!-- /.row -->
    </div>
    <!-- /.col-lg-12 -->
  </div>
  <!-- /.row -->
</div>
<!-- End: Page Content -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>